repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.4.4
    hooks:
    - id: pylint
      args: [--load-plugins=pylint.extensions.mccabe, guet]
  - repo: https://github.com/PyCQA/isort
    rev: 4.3.21
    hooks:
    - id: isort
      args: [--check-only]
      always_run: true
      files: \.(py)$
      entry: isort ./guet/**/*.py --check-only
      pass_filenames: false
    - id: isort
      args: [--check-only]
      always_run: true
      files: \.(py)$
      entry: isort ./e2e/**/*.py --check-only
      pass_filenames: false
    - id: isort
      args: [--check-only]
      always_run: true
      files: \.(py)$
      entry: isort ./test/**/*.py --check-only
      pass_filenames: false
  - repo: local
    hooks:
    -   id: unit-tests
        name: unit-tests
        entry: python3 -m unittest discover test
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
    -   id: e2e-tests
        name: e2e-tests
        entry: unittest-parallel --start-directory e2e -t .
        language: system
        types: [python]
        always_run: true
        stages: [push]
        pass_filenames: false
