name: guetci

on: ['push', 'pull_request']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        pylint --load-plugins=pylint.extensions.mccabe guet
    - name: Test
      run: |
        python -m unittest discover test
        python -m unittest discover e2e
